step1
Hyeon9mak/kotlin-racingcar pull request #1
Opened 2023-07-06 14:24 UTC by dhslrl321

2023-07-06 14:24 UTC, dhslrl321 commented on src/test/kotlin/com/github/dhslrl321/PersonTest.kt
> +        )
`allSatisfy` 안돼요 흑흑

2023-07-08 04:13 UTC, Hyeon9mak requested changes
안녕하세요 원익님, 1단계 진행 고생하셨어요.
별개로 원익님 브랜치를 만들어드릴테니 그쪽으로 병합 브랜치를 변경해보면 좋을 것 같아요.
간단한 코멘트 몇 가지 남겼으니 확인해주세요.
궁금하신 점 언제든지 코멘트, DM 주세요 🙇‍♂️

2023-07-08 04:13 UTC, Hyeon9mak commented on src/main/kotlin/com/github/dhslrl321/NullablePerson.kt
> +}
`Editor` > `General` > `Ensure every saved file ends with a line break`
자꾸 EOF 보이면 리뷰 안해드립니다 ㅎ.ㅎ
![image](https://github.com/Hyeon9mak/kotlin-racingcar/assets/37354145/f1e08cc9-b1be-40b0-90ac-55e0fb44ddb7)

2023-07-08 04:13 UTC, Hyeon9mak commented on src/test/kotlin/com/github/dhslrl321/DataClassPersonTest.kt
> +    }
학습을 위해서 kotest matcher 들을 활용해보는 것도 좋을 것 같아요.
`shouldBe` 를 활용해보면 어떨까요?

2023-07-08 04:13 UTC, Hyeon9mak commented on src/test/kotlin/com/github/dhslrl321/PersonTest.kt
> +        )
io.kotest.inspectors.forAll 로 대체해봐도 좋을 것 같아요 😄 

```kotlin
actual.forAll {
    // kotest matchers 검증
}
```

2023-07-08 04:13 UTC, Hyeon9mak commented on src/main/kotlin/com/github/dhslrl321/NullablePerson.kt
> +) {
코틀린 학습 테스트 예시 문제에서는 하나의 data class 로 여러가지 테스트를 수행하는 것 같았어요.
예시 문제와 마찬가지로 하나의 data class 로 여러 테스트를 수행해주는 건 어떨까요?

2023-07-10 00:28 UTC, dhslrl321 commented on src/main/kotlin/com/github/dhslrl321/NullablePerson.kt
> +}
현구님 eof 를 왜 하는거에요?
왜 해야하는지에 대한 공감이 없는 상태라서 ㅎㅎ

2023-07-10 12:58 UTC, Hyeon9mak commented on src/main/kotlin/com/github/dhslrl321/NullablePerson.kt
> +}
- https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/

요 블로그에서 잘 설명해주는 것 같아요.

> -  UNIX의 표준으로는 파일 마지막에 개행이 있어야한다.
> - 잠재적인 문제가 될 수 있다.

2023-07-12 13:47 UTC, dhslrl321 commented
step 1 인데도 꽤 늦었네요 ㅎ.. 개인시간에 제 코드 봐주셔서 감사해요

2023-07-16 12:52 UTC, Hyeon9mak approved these changes
고생하셨어요! 다음 단계로 넘어가시죠!

2023-07-16 12:52 UTC, merged

2023-07-19 13:19 UTC, dhslrl321 commented
step 2 는 어디서 확인할 수 있나요!